[versions]
agp = "8.2.2"

[libraries]

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }

[bundles]

